Traceback (most recent call last):
  File "/mnt/qb/work/butz/svolz67/dev/models/master/./runNormalize.py", line 198, in <module>
    dataloader, validation = mapDataset(datasetTrain, datasetVal, batch_size)
  File "/mnt/qb/work/butz/svolz67/dev/models/master/./runNormalize.py", line 142, in mapDataset
    train = DataLoader(dataset=Wave("wave-5000-90"), batch_size=batch_size, shuffle=True, drop_last=True,
  File "/mnt/qb/work/butz/svolz67/dev/models/master/./runNormalize.py", line 26, in __init__
Traceback (most recent call last):
  File "/mnt/qb/work/butz/svolz67/dev/models/master/./runNormalize.py", line 198, in <module>
    f = h5py.File("../data/wave/" + file, 'r')
  File "/mnt/qb/work/butz/svolz67/envs/lib/python3.10/site-packages/h5py/_hl/files.py", line 507, in __init__
    dataloader, validation = mapDataset(datasetTrain, datasetVal, batch_size)
  File "/mnt/qb/work/butz/svolz67/dev/models/master/./runNormalize.py", line 142, in mapDataset
    train = DataLoader(dataset=Wave("wave-5000-90"), batch_size=batch_size, shuffle=True, drop_last=True,
  File "/mnt/qb/work/butz/svolz67/dev/models/master/./runNormalize.py", line 26, in __init__
    f = h5py.File("../data/wave/" + file, 'r')
  File "/mnt/qb/work/butz/svolz67/envs/lib/python3.10/site-packages/h5py/_hl/files.py", line 507, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/mnt/qb/work/butz/svolz67/envs/lib/python3.10/site-packages/h5py/_hl/files.py", line 220, in make_fid
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/mnt/qb/work/butz/svolz67/envs/lib/python3.10/site-packages/h5py/_hl/files.py", line 220, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 106, in h5py.h5f.open
  File "h5py/h5f.pyx", line 106, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = '../data/wave/wave-5000-90', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = '../data/wave/wave-5000-90', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Traceback (most recent call last):
  File "/mnt/qb/work/butz/svolz67/dev/models/master/./runNormalize.py", line 198, in <module>
    dataloader, validation = mapDataset(datasetTrain, datasetVal, batch_size)
  File "/mnt/qb/work/butz/svolz67/dev/models/master/./runNormalize.py", line 142, in mapDataset
    train = DataLoader(dataset=Wave("wave-5000-90"), batch_size=batch_size, shuffle=True, drop_last=True,
  File "/mnt/qb/work/butz/svolz67/dev/models/master/./runNormalize.py", line 26, in __init__
    f = h5py.File("../data/wave/" + file, 'r')
  File "/mnt/qb/work/butz/svolz67/envs/lib/python3.10/site-packages/h5py/_hl/files.py", line 507, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/mnt/qb/work/butz/svolz67/envs/lib/python3.10/site-packages/h5py/_hl/files.py", line 220, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 106, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = '../data/wave/wave-5000-90', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Traceback (most recent call last):
  File "/mnt/qb/work/butz/svolz67/dev/models/master/./runNormalize.py", line 198, in <module>
    dataloader, validation = mapDataset(datasetTrain, datasetVal, batch_size)
  File "/mnt/qb/work/butz/svolz67/dev/models/master/./runNormalize.py", line 142, in mapDataset
    train = DataLoader(dataset=Wave("wave-5000-90"), batch_size=batch_size, shuffle=True, drop_last=True,
  File "/mnt/qb/work/butz/svolz67/dev/models/master/./runNormalize.py", line 26, in __init__
    f = h5py.File("../data/wave/" + file, 'r')
  File "/mnt/qb/work/butz/svolz67/envs/lib/python3.10/site-packages/h5py/_hl/files.py", line 507, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/mnt/qb/work/butz/svolz67/envs/lib/python3.10/site-packages/h5py/_hl/files.py", line 220, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 106, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = '../data/wave/wave-5000-90', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Traceback (most recent call last):
  File "/mnt/qb/work/butz/svolz67/dev/models/master/./runNormalize.py", line 198, in <module>
    dataloader, validation = mapDataset(datasetTrain, datasetVal, batch_size)
  File "/mnt/qb/work/butz/svolz67/dev/models/master/./runNormalize.py", line 142, in mapDataset
    train = DataLoader(dataset=Wave("wave-5000-90"), batch_size=batch_size, shuffle=True, drop_last=True,
  File "/mnt/qb/work/butz/svolz67/dev/models/master/./runNormalize.py", line 26, in __init__
    f = h5py.File("../data/wave/" + file, 'r')
  File "/mnt/qb/work/butz/svolz67/envs/lib/python3.10/site-packages/h5py/_hl/files.py", line 507, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/mnt/qb/work/butz/svolz67/envs/lib/python3.10/site-packages/h5py/_hl/files.py", line 220, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 106, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = '../data/wave/wave-5000-90', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
