Traceback (most recent call last):
  File "/mnt/qb/work/butz/svolz67/dev/convLSTM/speed/./trainRange.py", line 219, in <module>
    datasetTrainLower = Wave(datasetNameLower)
  File "/mnt/qb/work/butz/svolz67/dev/convLSTM/speed/./trainRange.py", line 26, in __init__
    f = h5py.File("../../data/wave/" + file, 'r')
  File "/mnt/qb/work/butz/svolz67/envs/lib/python3.10/site-packages/h5py/_hl/files.py", line 507, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/mnt/qb/work/butz/svolz67/envs/lib/python3.10/site-packages/h5py/_hl/files.py", line 220, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 106, in h5py.h5f.open
BlockingIOError: [Errno 11] Unable to open file (unable to lock file, errno = 11, error message = 'Resource temporarily unavailable')
